# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e830b0be615caa83d44e3574584aaec2f4e1faa7d5e34da3e960ba3421f898158ac90b600a7d9e680d655c6ec12540c3dcbeeeb95cb4ae168bddcdcf2c4b1d59

test:
  secret_key_base: bd70fa66e14a53a065e5a092e1ac744d82b1ba049a99f398deefd687df0ab3b7df066fb21a673b84f10a177de13e47e1c3af44b9335da1e14dba6a402962af4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
